### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MoxxiFX** [kivaar/long-live#3]
in the .exe when you press stop, a popup says "this will corrupt your data" what does that mean? is it referring to the gallery files your downloading?

**Comment by kivaar** [comment]
Hey Moxxi! That's a generic warning which is part of the PyInstaller application. So in this case, you're right - it refers to the gallery files. At worst, you might get a partial or corrupted file which would be the image that was in the middle of being downloaded. It's not harmful, I've stopped the script halfway many times :)
