### ISSUE TITLE
Album downloads stopping randomly

### ISSUE THREAD

**Issue by MoxxiFX** [kivaar/long-live#6]
I've been using this for a while now, and I'd like to say Thankyou so much for making this program kivaar. It's made my life so much easier. I'm using the exe and when the program is saving a large album, it can sometimes stop randomly and will just sit there and not show anything happening in the status box. I open the folder it's stuck on and all the pictures are downloaded but it's as if they haven't registered on the program yet. I encounter this issue almost every time I use it. I usually just restart the program and try again which can fix it but that's not ideal if I leave the downloads unmonitored and it gets stuck on a single album for hours. instead of skipping it.

A potential fix to this would be to add a "timeout" to downloads for example, when an album has been downloading for so long (~1 minute) and no photos have been added since the last saved photo, then it would skip that photo/album and after it's completed saving the albums, a box showing which albums were skipped appears so you can try it saving them again.

**Comment by kivaar** [comment]
Hey Moxxi! Thanks for the kind words. It's good to know that a random script I wrote as a web scraping exercise is useful to you. An actual pop-up box might be beyond my ability, but the rest seems doable. I would like to replicate your issue to try and see what's happening. Some example inputs that get stuck early on would be great. I'm kivaar#7709 on Discord if you'd like to chat there.

**Comment by MoxxiFX** [comment]
Sure, as you can see below I've pasted the last two entries before it gets stuck. I have tried restarting the program multiple times, I've also tried deleting the folder that its stuck on and letting the program redownload it only to get stuck again.
As you can see in this screenshot the program says saving but the photos are already saved. (102) in folder.
https://i.imgur.com/xEuSshv.png

SAVING
|-- https://arianatoday.net/gallery/thumbnails.php?album=1398
|-- Home/Tours & Concerts/The Honeymoon Tour (2015)/Meet & Greet/Oct 15 - El Paso, TX (Meet & Greet)
|   |-- PAGE 1 - SKIPPED
|   |-- PAGE 2 - SKIPPED
SAVING
|-- https://arianatoday.net/gallery/thumbnails.php?album=1393

**Comment by kivaar** [comment]
Okay this was an interesting one. What's happening here, or at least in your example, is that the program output stops when it encounters a special character in an album name (the é in México), although the actual script will continue to run but may freeze soon after.

It seems to be PyInstaller (the tool that builds the executable) that is having trouble printing these special Unicode characters because it works just fine when I run the Python code.

I've put a workaround in [v0.2.1-beta](https://github.com/kivaar/long-live/releases/tag/v0.2.1-beta). Give it a whirl for a few days and let me know if it still gets stuck randomly. If not, then it's likely been stopping on fancy album names for when Ari visits foreign countries 😂

**Comment by MoxxiFX** [comment]
Thank you very much for your help in finding a fix. I tried V0.2.1 with the same URL and unfortunately it is still getting stuck on "saving". I checked and all the photos are downloaded, so I gave it about 45 minutes and it hadn't changed from saving.

I tried a different category and it got stuck once more on a different URL that didn't have any special characters in the title.

Here are the two albums that got stuck.
https://arianatoday.net/gallery/thumbnails.php?album=364
https://arianatoday.net/gallery/thumbnails.php?album=1393

**Comment by kivaar** [comment]
Hmm that's strange. I was able to download all of the meet and greet albums without it stopping (and it ran for quite a while). Are you getting anything past the "saving" message if you download just the two albums you linked individually?

Try running the code as well to see if you get the same problem. You can download everything as a zip on the main page and you will need Python 3 installed.

To install the extra modules first:
```
pip install -r requirements.txt
```
To run the code:
```
python scraper_gui.py
```

**Comment by MoxxiFX** [comment]
I tried both links individually and it still got stuck on saving, I also tried deleting both folders and still got stuck.
I added you on discord, if you want to chat there.
